# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photograph_judge_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='password',
            field=models.CharField(default='aotawmrialfrdwc', max_length=20),
        ),
    ]
