# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photograph_judge_system', '0003_auto_20161217_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='titie',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
