# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photograph_judge_system', '0004_auto_20161217_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='internal_identifier',
            field=models.CharField(default='hall 1', max_length=100),
            preserve_default=False,
        ),
    ]
