# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photograph_judge_system', '0005_entry_internal_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='internal_identifier',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='internal_identifier',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
